#!/usr/bin/env python3
# regenerate-skill-index.py — 掃描 .claude/skills/*/SKILL.md，重生
# .claude/skills/INDEX.md 的 AUTO-GENERATED 區段。
#
# 設計來源：vexjoy-agent scripts/generate-skill-index.py（簡化版，無 PyYAML 依賴）。
# zdpos consumer 版本：
#   - INDEX 用 Markdown 表格（不是 JSON），與 zdpos `.claude/{agents,commands}/INDEX.md` 一致
#   - START/END marker 保留手寫前後文（與 `.claude/artifacts/graduation-candidates.md` 同模式）
#   - 不引入 PyYAML，避免 dev 機 python 環境差異
#
# Usage:
#   python3 .claude/scripts/regenerate-skill-index.py            # 重生
#   python3 .claude/scripts/regenerate-skill-index.py --check    # dry-run；exit 1=需更新
#
# 在 hook 中由 .claude/hooks/post-edit-skill-index.sh 觸發；亦可手動執行。
# Exit codes: 0=已同步或更新完成 / 1=--check 偵測到 drift / 2=結構錯誤（INDEX.md 缺失 / marker 不對）。

import os
import re
import sys
from pathlib import Path

ROOT = Path(os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()).resolve()
SKILLS_DIR = ROOT / ".claude" / "skills"
INDEX_MD = SKILLS_DIR / "INDEX.md"
START = "<!-- AUTO-GENERATED:START -->"
END = "<!-- AUTO-GENERATED:END -->"
MAX_DESC_LEN = 200


def parse_frontmatter(text):
    """簡易 YAML frontmatter parser。

    僅處理 zdpos SKILL.md 已知格式：
      ---
      name: <slug>
      description: <one-line or quoted multi-line>
      <其他欄位忽略>
      ---

    不引入 PyYAML，避免 dev 機 python3 環境差異（zdpos Docker pos_php 內無 PyYAML）。
    """
    if not text.startswith("---"):
        return {}
    # 找關閉的 `---`（必須在獨立行）
    m = re.search(r"\n---\s*(?:\n|$)", text[3:])
    if not m:
        return {}
    fm_text = text[3 : 3 + m.start()]
    out = {}
    cur_key = None
    cur_buf = []
    for raw in fm_text.splitlines():
        # 新 key 必須頂格、形如 `key:`
        km = re.match(r"^([a-zA-Z_][a-zA-Z0-9_-]*):\s*(.*)$", raw)
        if km and not raw.startswith((" ", "\t")):
            if cur_key is not None:
                out[cur_key] = "\n".join(cur_buf).strip().strip('"').strip("'")
            cur_key = km.group(1)
            cur_buf = [km.group(2)]
        elif cur_key is not None:
            cur_buf.append(raw)
    if cur_key is not None:
        out[cur_key] = "\n".join(cur_buf).strip().strip('"').strip("'")
    return out


def collect_skills():
    """回傳 [(name, description, is_symlink), ...]，依 name asc。

    遞迴掃描（rglob），涵蓋巢狀 skill family（如 `gitnexus/*/SKILL.md`
    兩層結構），非僅單層 `.claude/skills/*/SKILL.md`。巢狀 skill 的 name
    加上子目錄前綴（如 `gitnexus/gitnexus-exploring`）。
    """
    skills = []
    if not SKILLS_DIR.exists():
        return skills
    skill_mds = sorted(
        SKILLS_DIR.rglob("SKILL.md"),
        key=lambda p: str(p.relative_to(SKILLS_DIR)).lower(),
    )
    for skill_md in skill_mds:
        rel_dir = skill_md.parent.relative_to(SKILLS_DIR)
        # symlink 可能指向 ../../.agents/skills/* 或外部位置；以頂層目錄判斷
        top_dir = SKILLS_DIR / rel_dir.parts[0]
        try:
            text = skill_md.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        fm = parse_frontmatter(text)
        base_name = fm.get("name") or rel_dir.parts[-1]
        if len(rel_dir.parts) > 1:
            name = "/".join(rel_dir.parts[:-1]) + "/" + base_name
        else:
            name = base_name
        desc = fm.get("description") or "(no description)"
        # 壓平多行 + 截長
        desc = re.sub(r"\s+", " ", desc).strip()
        if len(desc) > MAX_DESC_LEN:
            desc = desc[: MAX_DESC_LEN - 3] + "..."
        skills.append((name, desc, top_dir.is_symlink()))
    return skills


def group_skills(skills):
    """三組分桶：zdpos-* / openspec-* / 其他。"""
    g_zdpos, g_openspec, g_other = [], [], []
    for item in skills:
        name = item[0]
        if name.startswith("zdpos-"):
            g_zdpos.append(item)
        elif name.startswith("openspec-"):
            g_openspec.append(item)
        else:
            g_other.append(item)
    return g_zdpos, g_openspec, g_other


def render_section(title, items):
    if not items:
        return ""
    out = [f"### {title}", "", "| Skill | Description |", "|---|---|"]
    for name, desc, sym in items:
        marker = " *(symlink)*" if sym else ""
        d = desc.replace("|", "\\|")
        out.append(f"| `{name}`{marker} | {d} |")
    out.append("")
    return "\n".join(out)


def build_block():
    """構造 AUTO-GENERATED 區段內容（不含時間戳——避免 --check 永遠偵測 drift）。

    「上次重生時間」資訊改放 INDEX.md mtime / git log；不嵌入內容。
    """
    skills = collect_skills()
    z, o, x = group_skills(skills)
    lines = [
        "_Auto-generated by `.claude/scripts/regenerate-skill-index.py` "
        "(run `--check` to detect drift; INDEX.md mtime indicates last regenerate)._",
        "",
        f"Total: **{len(skills)}** skills "
        f"({len(z)} zdpos-* / {len(o)} openspec-* / {len(x)} other)",
        "",
    ]
    for title, items in (
        ("zdpos-specific", z),
        ("OpenSpec plugin", o),
        ("Other (bundled / adaptive)", x),
    ):
        sec = render_section(title, items)
        if sec:
            lines.append(sec)
    return "\n".join(lines).rstrip() + "\n"


def update_index_md(check_only=False):
    if not INDEX_MD.exists():
        sys.stderr.write(f"[regenerate-skill-index] INDEX.md missing: {INDEX_MD}\n")
        return 2
    text = INDEX_MD.read_text(encoding="utf-8")
    i = text.find(START)
    j = text.find(END)
    if i < 0 or j < 0 or j < i:
        sys.stderr.write(
            f"[regenerate-skill-index] markers missing in INDEX.md "
            f"(need '{START}' ... '{END}')\n"
        )
        return 2
    new_block = f"{START}\n\n{build_block()}\n{END}"
    new_text = text[:i] + new_block + text[j + len(END) :]
    if new_text == text:
        return 0
    if check_only:
        return 1
    tmp = INDEX_MD.with_suffix(INDEX_MD.suffix + ".tmp")
    tmp.write_text(new_text, encoding="utf-8")
    os.replace(tmp, INDEX_MD)
    return 0


def main():
    check = "--check" in sys.argv
    rc = update_index_md(check_only=check)
    if rc == 0:
        msg = "synced" if not check else "in-sync"
        print(f"[regenerate-skill-index] {msg} — {INDEX_MD}")
    elif rc == 1:
        print("[regenerate-skill-index] DRIFT — INDEX.md needs regeneration", file=sys.stderr)
    sys.exit(rc)


if __name__ == "__main__":
    main()
